In [1]:
import numpy as np

In [2]:
matrix = np.empty(shape=[0,3])

In [7]:
point = np.asarray([1,2,3])

In [11]:
matrix = np.vstack([matrix,point])
print matrix

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]


In [12]:
# load trajectories
kinectTraj = np.loadtxt('../baxter_ws/src/kinect_baxter_calibration/files/kinect_trajectory', 
                        delimiter=',')
baxterTraj = np.loadtxt('../baxter_ws/src/kinect_baxter_calibration/files/baxter_trajectory', 
                        delimiter=',')

In [93]:
x = kinectTraj
y = baxterTraj

In [94]:
nSamples = x.shape[0]

In [95]:
xMean = x.mean(axis=0)
yMean = y.mean(axis=0)

In [96]:
xTemp = x - xMean
yTemp = y - yMean

In [97]:
covarMatrix = np.dot(yTemp.T,xTemp)

In [98]:
U,D,V = np.linalg.svd(covarMatrix)

In [99]:
S = np.diag(np.asarray([1,1,np.sign(np.linalg.det(V)*np.linalg.det(U))]))

In [100]:
R = np.dot(U,S)
R = np.dot(R,V.T)

In [101]:
c = np.trace(np.dot(np.diag(D),S))/np.sum(xTemp**2)
c = 1

In [102]:
t = yMean - c*np.dot(R,xMean)
print t

[ 1.23430599 -0.39732338  0.62015926]


In [103]:
xout = c*np.dot(R,x.T).T + t

In [104]:
errs = np.sqrt(np.sum((y - xout)**2,axis=1))
err = errs.sum()/nSamples

print err

0.102321377416
